version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexa-postgres
    environment:
      POSTGRES_USER: nexa
      POSTGRES_PASSWORD: nexa123
      POSTGRES_DB: nexa_tasks
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexa"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexa-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://nexa:nexa123@postgres:5432/nexa_tasks
    ports:
      - "8002:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexa-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8002
    ports:
      - "3002:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
